#spring:
#  application:
#    name: Shopping
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/project
#    username: root
#    password: 123456
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      properties:
#        hibernate:
#          format_sql: true
#          show_sql: true
#          dialect: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql
#
#
